[package]
name = "mouse-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.48", features = ["Win32_Devices_DeviceAndDriverInstallation", "Win32_Foundation", "Win32_Security"] }
